### ISSUE TITLE
Create config system

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/ReCoDe-spatial-transcriptomics#55]
The users should be able to define certain variables via a config file.

I will do this using pydantic to define a config that will be able to validate the config file.

**Comment by AdrianDAlessandro** [comment]
Ok that looks great! We can do the same thing in Python quite easily. If you're happy with the YAML file format, we can stick with that. Otherwise, we can use [TOML](https://toml.io/en/) (the main reason for this is TOML is built in to Python and the syntax is slightly closer to Python, whereas YAML requires an external library).

Syntax Comparison:

YAML
```yaml
######### 01_Read_in_data #########
# load data
path_to_data: "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data"
path_to_meta: "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data/meta_data/meta.xlsx"
sheet_name: "meta_IMC"
images_path: "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data/img/"
mask_path: "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data/illastik_cellprofiler/masks/"

# markers to remove
markers_to_remove:
  - "CollagenI"
  - "CollagenIII"
  - "CollagenVI"
  - "CollagenIV"
  - "DNA1"
  - "DNA2"
```

TOML
```toml
######### 01_Read_in_data #########
# load data
path_to_data = "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data"
path_to_meta = "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data/meta_data/meta.xlsx"
sheet_name = "meta_IMC"
images_path = "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data/img/"
mask_path = "/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/COPD_CO_IMC/data/illastik_cellprofiler/masks/"

# markers to remove
markers_to_remove = [
    "CollagenI",
    "CollagenIII",
    "CollagenVI",
    "CollagenIV",
    "DNA1",
    "DNA2",
]
```
